//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaSP.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliotecaSP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250617_2318_Gestión_de_Usuarios_Biblioteca_simple_compose_01jy0qfy15fwxseab79v400gv2 {
            get {
                object obj = ResourceManager.GetObject("20250617_2318_Gestión de Usuarios Biblioteca_simple_compose_01jy0qfy15fwxseab79v4" +
                        "00gv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_0128_प्राचीन_कालद्वार_का_रहस्य_simple_compose_01jy3h9q0qfac86k8cwsw55c0j {
            get {
                object obj = ResourceManager.GetObject("20250619_0128_प्राचीन कालद्वार का रहस्य_simple_compose_01jy3h9q0qfac86k8cwsw55c0j" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_0129_Bibliothèque_Universitaire_Ambiance_simple_compose_01jy3hbk8wfqmbpbwdqk7z0d4j {
            get {
                object obj = ResourceManager.GetObject("20250619_0129_Bibliothèque Universitaire Ambiance_simple_compose_01jy3hbk8wfqmbpb" +
                        "wdqk7z0d4j", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1738_Gestión_de_Biblioteca_simple_compose_01jy58vrm0egxt6rnn4abnf5c2 {
            get {
                object obj = ResourceManager.GetObject("20250619_1738_Gestión de Biblioteca_simple_compose_01jy58vrm0egxt6rnn4abnf5c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1749_Chiaroscuro_Hands_and_Book_simple_compose_01jy59hejjfcrrp61rgthtw42h {
            get {
                object obj = ResourceManager.GetObject("20250619_1749_Chiaroscuro Hands and Book_simple_compose_01jy59hejjfcrrp61rgthtw42" +
                        "h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1755_Hands_with_Vintage_Book_simple_compose_01jy59vh2fe74tmzr7xabst5q6 {
            get {
                object obj = ResourceManager.GetObject("20250619_1755_Hands with Vintage Book_simple_compose_01jy59vh2fe74tmzr7xabst5q6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1936_Bok_simple_compose_01jy5fnx3rfv9rgf209ay5hrb4 {
            get {
                object obj = ResourceManager.GetObject("20250619_1936_Bok_simple_compose_01jy5fnx3rfv9rgf209ay5hrb4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1951_Fachada_Biblioteca_Pública_simple_compose_01jy5gg6e6fyrtwhkr97qn6tnb {
            get {
                object obj = ResourceManager.GetObject("20250619_1951_Fachada Biblioteca Pública_simple_compose_01jy5gg6e6fyrtwhkr97qn6tn" +
                        "b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1951_Fachada_Biblioteca_Pública_simple_compose_01jy5gg6e6fyrtwhkr97qn6tnb1 {
            get {
                object obj = ResourceManager.GetObject("20250619_1951_Fachada Biblioteca Pública_simple_compose_01jy5gg6e6fyrtwhkr97qn6tn" +
                        "b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1953_Bibliotecario_en_Computadora_simple_compose_01jy5gjgche41b3eraw4fd23g3 {
            get {
                object obj = ResourceManager.GetObject("20250619_1953_Bibliotecario en Computadora_simple_compose_01jy5gjgche41b3eraw4fd2" +
                        "3g3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250619_1953_Bibliotecario_en_Computadora_simple_compose_01jy5gjgche41b3eraw4fd23g31 {
            get {
                object obj = ResourceManager.GetObject("20250619_1953_Bibliotecario en Computadora_simple_compose_01jy5gjgche41b3eraw4fd2" +
                        "3g31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250620_1146_Roles_en_la_Biblioteca_simple_compose_01jy772z15ed1ax56r8qh9xa68 {
            get {
                object obj = ResourceManager.GetObject("20250620_1146_Roles en la Biblioteca_simple_compose_01jy772z15ed1ax56r8qh9xa68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250621_0124_Swiss_Valley_Serenity_simple_compose_01jy8nyr3cefjbs8gw2grpky77 {
            get {
                object obj = ResourceManager.GetObject("20250621_0124_Swiss Valley Serenity_simple_compose_01jy8nyr3cefjbs8gw2grpky77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250621_0129_Chica_y_Reloj_Mental_simple_compose_01jy8p6pazfcash0r01ym9f5z0 {
            get {
                object obj = ResourceManager.GetObject("20250621_0129_Chica y Reloj Mental_simple_compose_01jy8p6pazfcash0r01ym9f5z0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250621_0129_Curious_Alice_in_Wonderland_simple_compose_01jy8p8rz0fkpswph82cf23cyn {
            get {
                object obj = ResourceManager.GetObject("20250621_0129_Curious Alice in Wonderland_simple_compose_01jy8p8rz0fkpswph82cf23c" +
                        "yn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar_usuario {
            get {
                object obj = ResourceManager.GetObject("agregar-usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anadir {
            get {
                object obj = ResourceManager.GetObject("anadir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anadir__1_ {
            get {
                object obj = ResourceManager.GetObject("anadir (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap biblioteca_en_linea {
            get {
                object obj = ResourceManager.GetObject("biblioteca-en-linea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap biblioteca_en_linea__1_ {
            get {
                object obj = ResourceManager.GetObject("biblioteca-en-linea (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap biblioteca_publica {
            get {
                object obj = ResourceManager.GetObject("biblioteca-publica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enterprise {
            get {
                object obj = ResourceManager.GetObject("enterprise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap equipo {
            get {
                object obj = ResourceManager.GetObject("equipo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expandir_pantalla {
            get {
                object obj = ResourceManager.GetObject("expandir-pantalla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap informatica {
            get {
                object obj = ResourceManager.GetObject("informatica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap informatica__1_ {
            get {
                object obj = ResourceManager.GetObject("informatica (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mas {
            get {
                object obj = ResourceManager.GetObject("mas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap signo_de_mas {
            get {
                object obj = ResourceManager.GetObject("signo-de-mas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sistemas {
            get {
                object obj = ResourceManager.GetObject("sistemas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
